spring:
  application:
    name: lms-platform

  datasource:
    url: jdbc:postgresql://localhost:5433/lms_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}        # ← УБРАЛИ дефолт, теперь переменная обязательна
  expiration: ${JWT_EXPIRATION:86400000}  # ← expiration можно оставить с дефолтом

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html